<?php 
//peyamFi tarih dizisi
$gunler = array("","Pazartesi","Salı","Çarşamba","Perşembe","Cuma","Cumartesi","Pazar");
$aylar = array("","Ocak","Şubat","Mart","Nisan","Mayıs","Haziran","Temmuz","Ağustos","Eylül","Ekim","Kasım","Aralık");


$lisan= array(//peyamFi lisan dizisi
	"Yönetici Sayfası",
	"Yazılarım",
	"Sayfalar",
	"Projeler",
	"Projeler",
	"Yazılar",
	"Projeler",
	"Galeriler",
	"Yorumlar",
	"Mesajlar",
	"Güvenli Çıkış",
	"Projeleri görüntüleyin, oluşturun",
	"Mevcut yazılarınıza bakın veya yeni yazı yazın",
	"Projeleri görüntüleyin veya Proje oluşturun",
	"Mevcut galerilere bakın veya yeni galeri oluşturun",
	"Mevcut sayfaları düzenleyin veya yeni sayfa oluşturun",
	"Yazılarınıza yapılan yorumlar",
	"Size gönderilen mesajlar",
	"Oturumunuzu kapatın",
	"Yaptığın Çalışmalar",
	"Proje Adı",
	"Projeyin Açıklaması",
	"Yeni Proje Oluştur",
	"Projeler",
	"Başlangıç Tarihi",
	"Proje Resmi (En 500px)",
	"Projeyi Ekle",
	"Proje Bulunamadı",
	"Oluşturulan Projeler",
	"%s isimli etkinliği silmek istediğinizden emin misiniz?",
	"Bitiş Tarihi",
	"Projenin Detayları",
	"Projeyi Güncelle",
	"Yeni Galeri Oluştur",
	"Galeri Adı",
	"Dosya Uzantıları (virgülle ayırın)",
	"Galeri Kaydet",
	"%s isimli galeriyi tüm içeriğiyle birlikte silmek istediğinizden emin misiniz?",
	"İçerik Yükle",
	"Galeri Bulunamadı",
	"Galerisinin Detayları",
	"Galeriyi Güncelle",
	"Dosya Türü",
	"Bu içeriği silmek istediğinizden emin misiniz?",
	"Lütfen dosya seçiniz",
	"Yazmış olduğun yazıların",
	"Yeni yazı yaz",
	"Başlık",
	"Yazı Metni",
	"En önemli yer (Vurgulama yazısı [50-160 karakter aralığında])",
	"%s yazısının detayları",
	"%s yazısını silmek istediğinizden emin misiniz?",
	"Yazmış olduğunuz yazı yok",
	"Yazıyı Ekle",
	"Yazıyı Güncelle",
	"Proje Kategorisi Oluştur",
	"Kategori Adı",
	"Yeni bir Proje ekle",
	"%s kategorisine yeni bir Proje ekle",
	"Proje başlığı",
	"Proje içeriği",
	"Proje görseli",
	"%s Proje kategorisi",
	"Proje Ekle",
	"Proje Güncelle",
	"%s kategorisini silmek istediğinizden emin misiniz?",
	"%s Projeini silmek istediğinizden emin misiniz?",
	"Proje Kategorileri",
	"Eklenmiş bir kategori bulunamadı!",
	"Projeler",
	"%s Projeinin detayları",
	"Proje görselini değiştir (değiştirmek istemiyorsanız boş bırakın)",
	"mB" => "Masaüstü » %s",
	"Sayfa Kategorisi Oluştur",
	"Kategori Adı",
	"Yeni bir sayfa ekle",
	"%s kategorisine yeni bir sayfa ekle",
	"Sayfa başlığı",
	"Sayfa içeriği",
	"Sayfa görseli (en: 800px)",
	"%s Sayfa kategorisi",
	"Sayfa Ekle",
	"Sayfa Güncelle",
	"%s kategorisini silmek istediğinizden emin misiniz?",
	"%s sayfasını silmek istediğinizden emin misiniz?",
	"Sayfa Kategorileri",
	"Eklenmiş bir kategori bulunamadı!",
	"Sayfalar",
	"%s sayfasının detayları",
	"Sayfa görselini değiştir (değiştirmek istemiyorsanız boş bırakın)",
	"Eklenmiş bir sayfa bulunamadı!",
	"Kategoriyi Oluştur",
	"Sayfayı Oluştur",
	"İlgili Galeri",
	"%s kategorisindeki %s",
	"Kullanıcı Adınız",
	"Şifreniz",
	"Oturum Aç",
	"Oturum Aç » %s",
	"Profil Ayarları",
	"Site Ayarları",
	"Bu Ayki Projeler",
	"Son Yazılarınız",
	"Son Projeler",
	"Bildirim Ayarları",
	"Hesap Bilgileriniz",
	"İmza Bilgisi",
	"Kişisel Profil Sayfanız",
	"E-Posta Adresiniz",
	"Adınız",
	"Soyadınız",
	"Şifre (Değiştirmek istemiyorsanız boş bırakın)",
	"Şifre (Tekrar)",
	"Değişiklikleri Kaydet",
	"Ziyaretçiler benim yazımı okuduklarında bildir",
	"Ziyaretçiler yazıma yorum yaptıklarında bildir",
	"Profil sayfama bakıldığında bildir",
	"Dosya Yöneticisi",
	"Bu sayfa yayında değil veya hatalı içerik erişimi",
	"icerikHata" => "İçerik bulunamadı",
	"En fazla okunan",
	"Son yorumlar",
	"En fazla takip edilen %s",
	"Henüz eklenmiş yorum bulunamadı",
	"Devamı için tıklayın",
	"Sonraki",
	"Önceki",
	"Büyüt",
	"Çıkış",
	"Multimedya",
	"Detaylar &raquo",
	"Yazarın biyografisi",
	"Yazarın iletişim bilgileri",
	"Bu yazı %s yazıldı",
	"Bu yazıya yorum yaz",
	"Büyült",
	"Küçült",
	"Yazarın diğer yazıları",
	"Bu Proje %s eklendi",
	"Bu Projei %s yazdı",
	"%s Projeleri",
	"Bu sayfaya yorum yaz",
	"Yazarın yazıları",
	"%s Hakkında",
	"Yeni Üye Formu",
	"Sitemize üye olmak için aşağıdaki formu doldurmanız yeterli!",
	"E-Posta Adresiniz",
	"Kaydol!",
	"Kimlik Bilgileriniz",
	"Mail Adresiniz",
	"Adınız",
	"Soyadınız",
	"Şifreniz",
	"Şifreniz (Tekrar)",
	"Kayıt işleminiz başarıyla tamamlandı! Aşağıdaki form vasıtasıyla oturum açabilirsiniz",
	"Geçersiz e-posta adresi",
	"Lütfen bu alanı doldurun",
	"Lütfen şifreyi buraya tekrar girin",
	"Şifreler uyuşmuyor",
	"Bu mail adresi sisteme kayıtlıdır. Lütfen başka bir mail adresi giriniz.",
	"Kullanıcı Paneli",
	"Giriş Yap",
	"Oturum açıldı!",
	"Lütfen bilgilerinizi kontrol ediniz!",
	"Üye olmak istiyorum",
	"Şifremi unuttum",
	"Çok kez hatalı giriş yaptınız! Bu yüzden bir süre giriş yapamayacaksınız",
	"Şu anda sitemizde köşe yazarı bulunmamaktadır.",
	"Oturumunuzu kapatmak istediğinizden emin misiniz?",
	"Evet, çıkmak istiyorum.",
	"Hayır, vazgeçtim.",
	"Profil Resmi (Değiştirmek istemiyorsanız boş bırakın)",
	"Şifre Değişikliği",
	"Eski Şifre",
	"Yeni Şifre",
	"Yeni Şifre (Tekrar)",
	"Şifre Bilgilerimi Güncelle",
	"Eski şifreniz hatalı tekrar deneyiniz",
	"Şifreniz başarılı bir şekilde güncellendi",
	"Şu an için herhangi bir etkinliğimiz yok",
	"Yazar hiç yazı yazmadı",
	"Şu anda bu bölüm aktif değil",
	"<strong>Sayın %s</strong><br>Kişisel oturumunuza hoşgeldiniz",
	"Multimedya Arşivimiz",
	"Bütün üyeler",
	"Yeni üye kaydı",
	"%s isimli üyenin bütün kaydını silmek istediğinizden emin misiniz?",
	"Köşe Yazarları",
	"Yazarlar sitede sizin belirlemiş olduğunuz sıralamaya göre dizilmiştir",
	"Sitede toplam %s üye bulunmaktadır",
	"Siteye dön",
	"Kişisel Profil Sayfanız"
	
);
 ?>